#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2012 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH:= $(call my-dir)
ifneq ($(TARGET_CPU_SMP),true)
@echo "You must choose TARGET_CPU_SMP=true\n"
endif

# libEGL_mali.so
include $(CLEAR_VARS)
LOCAL_POST_PROCESS_COMMAND := $(shell mkdir -p $(TARGET_OUT_SHARED_LIBRARIES)/egl)
include $(CLEAR_VARS)
LOCAL_POST_PROCESS_COMMAND := $(shell cp -av $(LOCAL_PATH)/lib/libEGL_mali.so $(TARGET_OUT_SHARED_LIBRARIES)/egl)

# libGLESv1_CM_mali.so
include $(CLEAR_VARS)
LOCAL_POST_PROCESS_COMMAND := $(shell mkdir -p $(TARGET_OUT_SHARED_LIBRARIES)/egl)
include $(CLEAR_VARS)
LOCAL_POST_PROCESS_COMMAND := $(shell cp -av $(LOCAL_PATH)/lib/libGLESv1_CM_mali.so $(TARGET_OUT_SHARED_LIBRARIES)/egl)

# libGLESv2_mali.so
include $(CLEAR_VARS)
LOCAL_POST_PROCESS_COMMAND := $(shell mkdir -p $(TARGET_OUT_SHARED_LIBRARIES)/egl)
include $(CLEAR_VARS)
LOCAL_POST_PROCESS_COMMAND := $(shell cp -av $(LOCAL_PATH)/lib/libGLESv2_mali.so $(TARGET_OUT_SHARED_LIBRARIES)/egl)

# libMali
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libMali
LOCAL_PREBUILT_LIBS := lib/libMali.so

include $(BUILD_MULTI_PREBUILT)

# libUMP
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libUMP
LOCAL_PREBUILT_LIBS := lib/libUMP.so

include $(BUILD_MULTI_PREBUILT)
